"""
Publishing Worker for AVENIQ AI Workers v3.1.
PipelinePhases: OBSERVE -> ACT.
Capabilities: platform_publishing, delivery_tracking.
"""

from typing import Dict, Any, List
from ai_workers.base_worker import BaseWorker, WorkerContext, WorkerOutput, PipelinePhase, Decision
from runtime.event_bus import global_event_bus


class PublishingWorker(BaseWorker):
    def __init__(self):
        super().__init__(
            name="PublishingWorker",
            capabilities=["platform_publishing", "delivery_tracking"],
            pipeline_phases=[
                PipelinePhase.OBSERVE, PipelinePhase.ACT
            ]
        )

    def act(self, context: WorkerContext, decision: Decision) -> WorkerOutput:
        from approval.telegram.sender import global_telegram_sender

        ctx_data = getattr(context, "data", {}) or {}
        if not isinstance(ctx_data, dict):
            ctx_data = {}

        # 1. Extract image path & fallback generation if missing
        import os
        creative_out = ctx_data.get("creative", {}) or ctx_data.get("carousel", {}) or {}
        image_path = creative_out.get("image_path") or creative_out.get("image_url") if isinstance(creative_out, dict) else None
        
        if image_path:
            image_path = os.path.abspath(str(image_path))
            
        if not image_path or not os.path.isfile(image_path):
            try:
                from image_generation.providers.pollinations import PollinationsImageProvider
                pol = PollinationsImageProvider()
                resp = pol.generate_image("AVENIQ AI enterprise multi-agent growth banner graphic", width=512, height=512)
                if resp.success:
                    image_path = os.path.abspath(resp.image_url_or_path)
            except Exception as e:
                image_path = None

        # 2. Extract platform copy outputs generated by Gemini AI
        def _get_copy(val):
            if not val:
                return None
            if isinstance(val, dict):
                if val.get("copy"): return val["copy"]
                if val.get("caption"): return val["caption"]
                arts = val.get("artifacts", [])
                if arts and isinstance(arts, list) and len(arts) > 0 and isinstance(arts[0], dict):
                    return arts[0].get("copy") or arts[0].get("caption")
            elif hasattr(val, "artifacts") and getattr(val, "artifacts"):
                arts = getattr(val, "artifacts")
                if arts and len(arts) > 0:
                    art = arts[0]
                    if isinstance(art, dict):
                        return art.get("copy") or art.get("caption")
            if isinstance(val, str) and val and "Executed" not in val:
                return val
            return None

        linkedin_text = _get_copy(ctx_data.get("linkedin")) or _get_copy(ctx_data.get("blog"))
        instagram_text = _get_copy(ctx_data.get("instagram"))
        facebook_text = _get_copy(ctx_data.get("facebook"))
        x_text = _get_copy(ctx_data.get("x"))
        hashtags_text = _get_copy(ctx_data.get("hashtags")) or "#AVENIQ #AIWorkforce #EnterpriseAI #AutonomousAI"

        obj_name = getattr(context, "objective", "AVENIQ AI Daily Growth & Marketing Pipeline")
        if not linkedin_text:
            linkedin_text = f"🚀 **AVENIQ AI Enterprise Growth**\n\nRevolutionizing autonomous AI agent orchestration with zero-fallback multi-provider DAG routing for {obj_name}.\n\n{hashtags_text}"
        if not instagram_text:
            instagram_text = f"✨ Next-gen Autonomous Multi-Agent AI System.\n\nAVENIQ AI executes real web research & market intel for {obj_name}.\n\n{hashtags_text}"
        if not facebook_text:
            facebook_text = f"🌐 **AVENIQ AI Announcement**\n\nScale enterprise operations with autonomous AI agents. Real-time web intelligence and automated content strategy."
        if not x_text:
            x_text = f"1/2 🚀 Exciting news from AVENIQ AI! Our autonomous AI engine now runs multi-agent DAG pipelines.\n\n2/2 Experience zero-mock, real-time multi-channel AI execution. #AVENIQ #AI"

        tg_res = {"ok": False, "description": "Not configured"}
        dispatched_count = 0

        if global_telegram_sender.is_configured:
            def _send_platform(title_icon, platform_name, text_content):
                full_text = f"{title_icon} <b>{platform_name.upper()} POST</b>\n\n{text_content}"
                if image_path and isinstance(image_path, str) and os.path.isfile(image_path):
                    if len(full_text) <= 1000:
                        res = global_telegram_sender.send_photo(image_path, caption=full_text)
                        if res.get("ok"): return True
                    # Fallback if text long or caption fails: send photo then message
                    global_telegram_sender.send_photo(image_path, caption=f"{title_icon} <b>AVENIQ AI {platform_name.upper()} CREATIVE ASSET</b>")
                    res_msg = global_telegram_sender.send_message(full_text, parse_mode="HTML")
                    return res_msg.get("ok", False)
                else:
                    res_msg = global_telegram_sender.send_message(full_text, parse_mode="HTML")
                    return res_msg.get("ok", False)

            if _send_platform("💼", "LinkedIn", linkedin_text): dispatched_count += 1
            if _send_platform("📸", "Instagram", instagram_text): dispatched_count += 1
            if _send_platform("🌐", "Facebook", facebook_text): dispatched_count += 1
            if _send_platform("🐤", "X (Twitter)", x_text): dispatched_count += 1

            tg_res = {"ok": True, "dispatched_channels": dispatched_count}

        msg_id = tg_res.get("result", {}).get("message_id") if tg_res.get("ok") else None

        artifact = {
            "title": f"Publishing Receipt: '{obj_name}'",
            "type": "PublishingReceipt",
            "channel": "Telegram",
            "image_path": image_path,
            "dispatched_count": dispatched_count,
            "status": "Delivered" if tg_res.get("ok") else "Skipped / Unconfigured",
            "telegram_response": tg_res
        }

        event_payload = {
            "goal_id": getattr(context, "goal_id", "exec_wf"),
            "channel": "Telegram",
            "ok": tg_res.get("ok", False)
        }
        global_event_bus.publish("CampaignPublished", event_payload)

        return WorkerOutput(
            status="success",
            artifacts=[artifact],
            events=[{"name": "CampaignPublished", "payload": event_payload}],
            metrics={"channels_published": dispatched_count}
        )


global_publishing_worker = PublishingWorker()
