"""
Publishing Worker for AVENIQ AI Workers v3.1.
PipelinePhases: OBSERVE -> ACT.
Capabilities: platform_publishing, delivery_tracking.
"""

from typing import Dict, Any, List
from ai_workers.base_worker import BaseWorker, WorkerContext, WorkerOutput, PipelinePhase, Decision
from runtime.event_bus import global_event_bus


class PublishingWorker(BaseWorker):
    def __init__(self):
        super().__init__(
            name="PublishingWorker",
            capabilities=["platform_publishing", "delivery_tracking"],
            pipeline_phases=[
                PipelinePhase.OBSERVE, PipelinePhase.ACT
            ]
        )

    def act(self, context: WorkerContext, decision: Decision) -> WorkerOutput:
        from approval.telegram.sender import global_telegram_sender

        ctx_data = getattr(context, "data", {}) or {}
        if not isinstance(ctx_data, dict):
            ctx_data = {}

        # 1. Extract image path & fallback generation if missing
        import os
        creative_out = ctx_data.get("creative", {}) or ctx_data.get("carousel", {}) or {}
        image_path = creative_out.get("image_path") or creative_out.get("image_url") if isinstance(creative_out, dict) else None
        
        if image_path:
            image_path = os.path.abspath(str(image_path))
            
        if not image_path or not os.path.isfile(image_path):
            try:
                from image_generation.providers.pollinations import PollinationsImageProvider
                pol = PollinationsImageProvider()
                resp = pol.generate_image("AVENIQ AI enterprise multi-agent growth banner graphic", width=512, height=512)
                if resp.success:
                    image_path = os.path.abspath(resp.image_url_or_path)
            except Exception as e:
                image_path = None

        # 2. Extract platform copy outputs generated by Gemini AI
        def _get_copy(val):
            if not val:
                return None
            if isinstance(val, dict):
                if val.get("copy"): return val["copy"]
                if val.get("caption"): return val["caption"]
                arts = val.get("artifacts", [])
                if arts and isinstance(arts, list) and len(arts) > 0 and isinstance(arts[0], dict):
                    return arts[0].get("copy") or arts[0].get("caption")
            elif hasattr(val, "artifacts") and getattr(val, "artifacts"):
                arts = getattr(val, "artifacts")
                if arts and len(arts) > 0:
                    art = arts[0]
                    if isinstance(art, dict):
                        return art.get("copy") or art.get("caption")
            if isinstance(val, str) and val and "Executed" not in val:
                return val
            return None

        linkedin_text = _get_copy(ctx_data.get("linkedin")) or _get_copy(ctx_data.get("blog"))
        instagram_text = _get_copy(ctx_data.get("instagram"))
        facebook_text = _get_copy(ctx_data.get("facebook"))
        x_text = _get_copy(ctx_data.get("x"))
        hashtags_text = _get_copy(ctx_data.get("hashtags")) or "#AVENIQ #AIWorkforce #EnterpriseAI #AutonomousAI"

        obj_name = getattr(context, "objective", "AVENIQ AI Daily Growth & Marketing Pipeline")
        if not linkedin_text:
            linkedin_text = f"🚀 **AVENIQ AI Enterprise Growth**\n\nRevolutionizing autonomous AI agent orchestration with zero-fallback multi-provider DAG routing for {obj_name}.\n\n{hashtags_text}"
        if not instagram_text:
            instagram_text = f"✨ Next-gen Autonomous Multi-Agent AI System.\n\nAVENIQ AI executes real web research & market intel for {obj_name}.\n\n{hashtags_text}"
        if not facebook_text:
            facebook_text = f"🌐 **AVENIQ AI Announcement**\n\nScale enterprise operations with autonomous AI agents. Real-time web intelligence and automated content strategy."
        if not x_text:
            x_text = f"1/2 🚀 Exciting news from AVENIQ AI! Our autonomous AI engine now runs multi-agent DAG pipelines.\n\n2/2 Experience zero-mock, real-time multi-channel AI execution. #AVENIQ #AI"

        tg_res = {"ok": False, "description": "Not configured"}
        dispatched_count = 0

        if global_telegram_sender.is_configured:
            # Header + Graphic
            main_header = f"🚀 <b>AVENIQ AI — Daily Content Pipeline Delivered</b>\n\n<b>Objective:</b> {obj_name}\n<b>Execution ID:</b> <code>{getattr(context, 'goal_id', 'exec_wf')}</code>"
            
            if image_path and isinstance(image_path, str):
                res_img = global_telegram_sender.send_photo(image_path, caption=main_header)
                if not res_img.get("ok"):
                    global_telegram_sender.send_message(main_header, parse_mode="HTML")
            else:
                global_telegram_sender.send_message(main_header, parse_mode="HTML")
            
            # Send separate platform messages
            msg_li = f"💼 <b>LINKEDIN POST</b>\n\n{linkedin_text}"
            res_li = global_telegram_sender.send_message(msg_li, parse_mode="HTML")
            if res_li.get("ok"): dispatched_count += 1

            msg_ig = f"📸 <b>INSTAGRAM POST</b>\n\n{instagram_text}"
            res_ig = global_telegram_sender.send_message(msg_ig, parse_mode="HTML")
            if res_ig.get("ok"): dispatched_count += 1

            msg_fb = f"🌐 <b>FACEBOOK POST</b>\n\n{facebook_text}"
            res_fb = global_telegram_sender.send_message(msg_fb, parse_mode="HTML")
            if res_fb.get("ok"): dispatched_count += 1

            msg_x = f"🐦 <b>X (TWITTER) POST</b>\n\n{x_text}"
            res_x = global_telegram_sender.send_message(msg_x, parse_mode="HTML")
            if res_x.get("ok"): dispatched_count += 1

            tg_res = {"ok": True, "dispatched_channels": dispatched_count}

        msg_id = tg_res.get("result", {}).get("message_id") if tg_res.get("ok") else None

        artifact = {
            "title": f"Publishing Receipt: '{obj_name}'",
            "type": "PublishingReceipt",
            "channel": "Telegram",
            "image_path": image_path,
            "dispatched_count": dispatched_count,
            "status": "Delivered" if tg_res.get("ok") else "Skipped / Unconfigured",
            "telegram_response": tg_res
        }

        event_payload = {
            "goal_id": getattr(context, "goal_id", "exec_wf"),
            "channel": "Telegram",
            "ok": tg_res.get("ok", False)
        }
        global_event_bus.publish("CampaignPublished", event_payload)

        return WorkerOutput(
            status="success",
            artifacts=[artifact],
            events=[{"name": "CampaignPublished", "payload": event_payload}],
            metrics={"channels_published": dispatched_count}
        )


global_publishing_worker = PublishingWorker()
